-- AUTO-GENERATED by minimal_init.lua
local busted = require('plenary.busted')
-- load each spec file into the same busted run:
dofile("spec/back_to_top_spec.lua")
dofile("spec/frontmatter_spec.lua")
dofile("spec/md_nav_spec.lua")
dofile("spec/minimal_init.lua")
dofile("spec/sections_spec.lua")
dofile("spec/toc_spec.lua")
